version: '3'
services:
  backend:
    restart: unless-stopped
    image: pavel-superstar:latest # name of the image
    container_name: my-backend # name of the container
    ports:
      - '80:80' # mapping ports of the container to the "outside"
    command: python3 main.py # command that starts the app
